# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeN <- function(t) {
    .Call('elves_computeN', PACKAGE = 'elves', t)
}

computeM <- function(t) {
    .Call('elves_computeM', PACKAGE = 'elves', t)
}

diff_days <- function(start, end) {
    .Call('elves_diff_days', PACKAGE = 'elves', start, end)
}

calc_sanctioned_hours <- function(start, duration) {
    .Call('elves_calc_sanctioned_hours', PACKAGE = 'elves', start, duration)
}

calc_unsanctioned_hours <- function(start, duration) {
    .Call('elves_calc_unsanctioned_hours', PACKAGE = 'elves', start, duration)
}

calc_p <- function(p0, n, m) {
    .Call('elves_calc_p', PACKAGE = 'elves', p0, n, m)
}

next_9am <- function(dtime) {
    .Call('elves_next_9am', PACKAGE = 'elves', dtime)
}

pickStart <- function(previousEnd, previousM, duration, productivity, threshold) {
    .Call('elves_pickStart', PACKAGE = 'elves', previousEnd, previousM, duration, productivity, threshold)
}

book_elf_c <- function(theArrival, theDuration, threshold) {
    .Call('elves_book_elf_c', PACKAGE = 'elves', theArrival, theDuration, threshold)
}
