# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateN <- function(t) {
    .Call('elves_CalculateN', PACKAGE = 'elves', t)
}

CalculateM <- function(t) {
    .Call('elves_CalculateM', PACKAGE = 'elves', t)
}

DateTimeAt900 <- function(date_time) {
    .Call('elves_DateTimeAt900', PACKAGE = 'elves', date_time)
}

DateTimeNext900 <- function(dtime) {
    .Call('elves_DateTimeNext900', PACKAGE = 'elves', dtime)
}

DateTimeAt1900 <- function(date_time) {
    .Call('elves_DateTimeAt1900', PACKAGE = 'elves', date_time)
}

CalculateDaysDifference <- function(start, end) {
    .Call('elves_CalculateDaysDifference', PACKAGE = 'elves', start, end)
}

CalcHours <- function(date_time) {
    .Call('elves_CalcHours', PACKAGE = 'elves', date_time)
}

CalculateSanctionedHours <- function(start, duration) {
    .Call('elves_CalculateSanctionedHours', PACKAGE = 'elves', start, duration)
}

CalculateUnsanctionedHours <- function(start, duration) {
    .Call('elves_CalculateUnsanctionedHours', PACKAGE = 'elves', start, duration)
}

CalculateP <- function(p0, n, m) {
    .Call('elves_CalculateP', PACKAGE = 'elves', p0, n, m)
}

NextSanctionedDateTime <- function(date_time) {
    .Call('elves_NextSanctionedDateTime', PACKAGE = 'elves', date_time)
}

CalculateDateTimeAfterResting <- function(previous_end, rest_period) {
    .Call('elves_CalculateDateTimeAfterResting', PACKAGE = 'elves', previous_end, rest_period)
}

CalculateDateTimeAfterResting2 <- function(previous_end, rest_period) {
    .Call('elves_CalculateDateTimeAfterResting2', PACKAGE = 'elves', previous_end, rest_period)
}

PickStart <- function(previous_start, previous_end, duration, productivity, threshold) {
    .Call('elves_PickStart', PACKAGE = 'elves', previous_start, previous_end, duration, productivity, threshold)
}

BookElf <- function(arrival, duration, threshold) {
    .Call('elves_BookElf', PACKAGE = 'elves', arrival, duration, threshold)
}

